blog/config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  devise_for :users
  get 'welcome/index'
   
  match '/Bprofile' => 'welcome#Bprofile', via: [:get]
  match '/Eprofile' => 'welcome#Eprofile', via: [:get]
  match '/Hprofile' => 'welcome#Hprofile', via: [:get]
  match '/Mprofile' => 'welcome#Mprofile', via: [:get]
  match '/Rprofile' => 'welcome#Rprofile', via: [:get]
  match '/Tprofile' => 'welcome#Tprofile', via: [:get]
  match '/Yprofile' => 'welcome#Yprofile', via: [:get]

 resources :articles do
  resources :comments
  end

  root 'welcome#index'

end

blog/app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

class CreateComments < ActiveRecord::Migration
  def change
    create_table :comments do |t|
      t.string :commenter
      t.text :body
 
      # this line adds an integer column called `article_id`.
      t.references :article, index: true
 
      t.timestamps null: false
    end
  end
end

blog/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

blog/app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
 
  def index
    @articles = Article.all
  end
 
  def show
    @article = Article.find(params[:id])
  end
 
  def new
    @article = Article.new
  end
 
  def edit
    @article = Article.find(params[:id])
  end
 
  def create
    @article = Article.new(article_params)
 
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end
 
  def update
    @article = Article.find(params[:id])
 
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
 
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
 
    redirect_to articles_path
  end
 
  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
 
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

blog/app/views/articles/edit.html.erb
<!DOCTYPE html>
<title>Edit Article</title>
<html>
<style>
  div[class="jumbotron"]{
    background:url("http://i.imgur.com/akCA66X.jpg");
    background-repeat: no-repeat;
    background-position: center;
  }
  div{
    background-color: lightgrey;
  }
 body {
 	text-align:center;
 }

</style>
<body>
<header>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
</header>

<div class="container">
<div class="jumbotron">
  <img src="http://i.imgur.com/6JE8FYq.png" align="left"/>
  
  <p><br><br><br></p> 

</div>
<div class="row">
<div class="col-md-4">

</div>
<div class="col-md-4">
  </div>
  <div class="col-md-4">
  </div>

</html>
<body>
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>
</body>

blog/app/views/articles/index.html.erb
<!DOCTYPE html>
<title>New Article</title>
<html>
<style>
  div[class="jumbotron"]{
    background:url("http://i.imgur.com/akCA66X.jpg");
    background-repeat: no-repeat;
    background-position: center;
  }
  div{
    background-color: lightgrey;
  }
  table {
  font-size: 20px;
}
   h1 {
    font-size: 30px;
   }
</style>
<body>
<header>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
</header>

<div class="container">
<div class="jumbotron">
  <img src="http://i.imgur.com/6JE8FYq.png" align="left"/>
  
  <p><br><br><br></p> 

</div>
<div class="row">
<div class="col-md-4">
</div>
<div class="col-md-4">
  <h1>Listing Articles</h1>

<table style="width:120%">
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show ', article_path(article) %></td>
      <td><%= link_to 'Edit ', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
    <%= link_to 'New article', new_article_path %>
  <div class="col-md-4">
  </div>
</div>
</html>

blog/app/views/articles/new.html.erb
<!DOCTYPE html>
<title>New Article</title>
<html>
<style>
  div[class="jumbotron"]{
    background:url("http://i.imgur.com/akCA66X.jpg");
    background-repeat: no-repeat;
    background-position: center;
  }
  div{
    background-color: lightgrey;
  }
 body {
 	text-align:center;
 }

</style>
<body>
<header>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
</header>

<div class="container">
<div class="jumbotron">
  <img src="http://i.imgur.com/6JE8FYq.png" align="left"/>
  
  <p><br><br><br></p> 

</div>
<div class="row">
<div class="col-md-4">

</div>
<div class="col-md-4">
  </div>
  <div class="col-md-4">
  </div>

</html>
<body>
<h1>New Article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>
</body>

blog/app/views/articles/show.html.erb
<!DOCTYPE html>
<title>Article Confirmation</title>
<html>
<style>
  div[class="jumbotron"]{
    background:url("http://i.imgur.com/akCA66X.jpg");
    background-repeat: no-repeat;
    background-position: center;
  }
  div{
    background-color: lightgrey;
  }
 body {
 	text-align:center;
 }

</style>
<body>
<header>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
</header>

<div class="container">
<div class="jumbotron">
  <img src="http://i.imgur.com/6JE8FYq.png" align="left"/>
  
  <p><br><br><br></p> 

</div>
<div class="row">
<div class="col-md-4">

</div>
<div class="col-md-4">
  </div>
  <div class="col-md-4">
  </div>

</html>
<body>
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
 
<h2>Comment</h2>
<%= render @article.comments %>
 
<h2>Add a comment:</h2>
<%= render 'comments/form' %>
 
<%= link_to 'Edit Article', edit_article_path(@article) %> |
<%= link_to 'Back to Articles', articles_path %>

</body>

blog/app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
 
<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

blog/app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

blog/app/views/ideas/_idea.html.erb
<% include_author       = true if local_assigns[:include_author].nil?
   this_belongs_to_self = user_signed_in? && idea.belongs_to_user?(current_user)
   self_voted_for_this  = user_signed_in? && current_user.voted_for?(idea) %>

<div class="idea-badge <%= 'idea-belongs-to-self' if this_belongs_to_self %>">
  <div class="idea-votes pull-left <%= 'user-has-voted' if self_voted_for_this %>">
    <div class="js-idea-votes-count" data-idea-id="<%= idea.id %>"><%= idea.total_votes %></div>
    <% unless this_belongs_to_self %>
      <div class="idea-vote-control">

      </div>
    <% end %>
  </div>
  <div class="idea-details">
    <h4 class="idea-title"><%= link_to idea.title, idea %></h4>
    <div class="idea-meta">
      <ul class="list-inline">
        <li class="idea-share-date">
          Shared 
            <% if include_author %>
              by <%= link_to idea.user.name, idea.user %>,
            <% end %>

            <%= distance_of_time_in_words_to_now(idea.created_at) %> ago
        </li>
      </ul>
    </div>
  </div>
</div>

blog/app/views/ideas/index.html.erb
<% content_for :page_title, "Browsing Ideas" %>

<%= render "shared/pagination", object: @ideas %>

<ul class="ideas list-unstyled">
  <%= render @ideas %>
</ul>

<%= render "shared/pagination", object: @ideas %>

blog/app/views/ideas/new.html.erb
<% content_for :page_title, "Share a new Idea" %>

<h1>Share a new Idea:</h1>

<%= simple_form_for(@idea) do |f| %>
  <div class="form-inputs">
    <div class="well">
      <%= f.input :title, label: "Title of your idea", input_html: { class: "input-lg" } %>
    </div>

    <%= f.input :body,  label: "Description of your idea", required: true,
                input_html: { rows: 6 } %>

    <small>
      <%= link_to "Markdown", "https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" %>
      is accepted!
    </small>
  </div>

  <div class="form-actions">
    <%= f.submit "Share this idea!", class: "btn btn-primary" %>
  </div>
<% end %>

blog/app/views/ideas/show.html.erb
<% content_for :page_title, "#{@idea.title} by #{@idea.user.name}" %>

<div class="idea">
  <header class="idea-header">
    <%= render @idea %>
  </header>

  <div class="row">

    <%# Idea body/markdown content: %>
    <div class="col-md-8">
      <div class="idea-document">
        <% unless @idea.body.empty? %>
          <%= sanitize UnsafeMarkdownPresenter.to_html(@idea.body) %>
        <% else %>
          <em>No description given :(</em>
        <% end %>
      </div>
    </div>

    <%# Sidebar %>
    <div class="col-md-4">

      <div class="idea-actions">
        <% unless @idea.belongs_to_user?(current_user) %>
          <section>
            <h4 class="section-title">Let's try something else...</h4>
            <p class="callout-paragraph">
              Do you want to take this idea in a different direction? Don't like where
              it is going? Copy it to your account and modify it to your liking!
            </p>

            <div class="well text-center">
              <%= link_to "#", class: "btn btn-primary btn-lg" do %>
                <i class="icon-code-fork"></i> Fork this Idea!
              <% end %>
            </div>
          </section>
        <% end %>

        <section>
          <h4 class="section-title">Share</h4>       
          <ul class="idea-social-actions list-inline">
            <%= link_to_share_to_twitter "#{@idea.title} by #{@idea.user.name} @ whatdo: #{idea_url(@idea)}",
                class: "social-badge twitter-social-badge", title: "Tweet this idea" do %>
              <i class="icon-twitter icon-large"></i>
            <% end %>
          </ul>
        </section>
      </div>
    </div>
  </div>
</div>

blog/app/views/ideas/vote.js.erb
// Gotta move this to the interface proper like:
$(".js-vote-callout").attr("disabled", true);
$(".js-idea-votes-count").text(<%= @idea.votes.size %>).parent().addClass("user-has-voted");

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</html>

blog/app/views/welcome/Bprofile.html.erb
<!DOCTYPE html>
<title>Mohamed Bahey</title>
<html>
<style>
a:link {
  float:right;
  color:navy;
  aligh: right;
    background-color:transparent;
    text-decoration:none;
}
a:visited {
  color:navy;
  align:right
    background-color:transparent;
    text-decoration:none;
}
a:hover {
    color:#ff0000;
    background-color:transparent;
    text-decoration:underline;
}
a:active {
    color:#ff0000;
    background-color:transparent;
    text-decoration:underline;
}
  div[class="jumbotron"]{
    background:url("http://i.imgur.com/akCA66X.jpg");
    background-repeat: no-repeat;
    background-position: center;
    font-color:white;
    text-align:center;
    font-size:20px;
  }
  div{
    background-color: lightgrey;
  }
  h{
  color:white;
  align:left;
  }
p1{
  color:white;
}
</style>
<body>
<header>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  </header>
<div class="container">
<div class="jumbotron">
<img style="width: 200px; height: 200px; border-radius: 150px;"
<img src="http://i.imgur.com/2ImfzDE.jpg?2" title="source: imgur.com" align="left"/>
<br>
    <h>Hello,</h>
    <p1>I'm Mohamed Bahey who is currently studying Business Informatics in the German University in Cairo.</p1>
</div>
<div class="row">

  <div class="col-md-4"> </div>
  <div class="col-md-4"> </div>
  </div>
  <div class="row">
  <div class="col-md-4">
  <h3 style="font-size:20px"><ins>Email:</ins></h3>
  <p>mohamedbaheyy@gmail.com</p>
  </div>
    <div class="col-md-4">
  <h4 style="font-size:20px"><ins>Phone Number:</ins></h4>
  <p>+201001833733</p>
  </div>
    <div class="col-md-4">
  <h5 style="font-size:20px"><ins>Date of Birth:</ins></h5>
  <p>9th of September,1994</p>
  </div>
  </div>
   <%= link_to 'Take me back home', controller: 'welcome' %>
</html>

blog/app/views/welcome/Eprofile.html.erb
<!DOCTYPE html>
<title>Seif Sayed</title>
<html>
<style>
a:link {
  float:right;
  color:navy;
  aligh: right;
    background-color:transparent;
    text-decoration:none;
}
a:visited {
  color:navy;
  align:right
    background-color:transparent;
    text-decoration:none;
}
a:hover {
    color:#ff0000;
    background-color:transparent;
    text-decoration:underline;
}
a:active {
    color:#ff0000;
    background-color:transparent;
    text-decoration:underline;
}
  div[class="jumbotron"]{
    background:url("http://i.imgur.com/akCA66X.jpg");
    background-repeat: no-repeat;
    background-position: center;
    font-color:white;
    text-align:center;
    font-size:20px;
  }
  div{
    background-color: lightgrey;
  }
  h{
  color:white;
  align:left;
  }
p1{
  color:white;
}
</style>
<body>
<header>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  </header>
<div class="container">
<div class="jumbotron">
<img style="width: 200px; height: 200px; border-radius: 150px;"
<img src="http://i.imgur.com/dVduMCKm.jpg?1" title="source: imgur.com" align="left"/>
<br>
    <h>Hello,</h>
    <p1>I'm Seif Sayed who is currently studying Business Informatics in the German University in Cairo.</p1>
</div>
<div class="row">

  <div class="col-md-4"> </div>
  <div class="col-md-4"> </div>
  </div>
  <div class="row">
  <div class="col-md-4">
  <h3 style="font-size:20px"><ins>Email:</ins></h3>
  <p>seif.enab@hotmail.com</p>
  </div>
    <div class="col-md-4">
  <h4 style="font-size:20px"><ins>Phone Number:</ins></h4>
  <p>+201221846210</p>
  </div>
    <div class="col-md-4">
  <h5 style="font-size:20px"><ins>Date of Birth:</ins></h5>
  <p>8th of May,1994</p>
  </div>
  </div>
  <%= link_to 'Take me back home', controller: 'welcome' %>
</html>

blog/app/views/welcome/Hprofile.html.erb
<!DOCTYPE html>
<title>Hossam Sameh</title>
<html>
<style>
a:link {
  float:right;
  color:navy;
  aligh: right;
    background-color:transparent;
    text-decoration:none;
}
a:visited {
  color:navy;
  align:right
    background-color:transparent;
    text-decoration:none;
}
a:hover {
    color:#ff0000;
    background-color:transparent;
    text-decoration:underline;
}
a:active {
    color:#ff0000;
    background-color:transparent;
    text-decoration:underline;
}
  div[class="jumbotron"]{
    background:url("http://i.imgur.com/akCA66X.jpg");
    background-repeat: no-repeat;
    background-position: center;
    font-color:white;
    text-align:center;
    font-size:20px;
  }
  div{
    background-color: lightgrey;
  }
  h{
  color:white;
  align:left;
  }
p1{
  color:white;
}
</style>
<body>
<header>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  </header>
<div class="container">
<div class="jumbotron">
<img style="width: 200px; height: 200px; border-radius: 150px;"
<img src="http://i.imgur.com/s84PyZW.jpg?1" title="source: imgur.com" align="left"/>
<br>
    <h>Hello,</h>
    <p1>I'm Hossam Sameh who is currently studying Business Informatics in the German University in Cairo. </p1>
</div>
<div class="row">

  <div class="col-md-4"> </div>
  <div class="col-md-4"> </div>
  </div>
  <div class="row">
  <div class="col-md-4">
  <h3 style="font-size:20px"><ins>Email:</ins></h3>
  <p>hossam@gmail.com</p>
  </div>
    <div class="col-md-4">
  <h4 style="font-size:20px"><ins>Phone Number:</ins></h4>
  <p>+201227878895</p>
  </div>
    <div class="col-md-4">
  <h5 style="font-size:20px"><ins>Date of Birth:</ins></h5>
  <p> 7th of August,1994</p>
  </div>
  </div>
  <%= link_to 'Take me back home', controller: 'welcome' %>
</html>

blog/app/views/welcome/Mprofile.html.erb
<!DOCTYPE html>
<title>Mariam Maher</title>
<html>
<style>
a:link {
  float:right;
  color:navy;
  aligh: right;
    background-color:transparent;
    text-decoration:none;
}
a:visited {
  color:navy;
  align:right
    background-color:transparent;
    text-decoration:none;
}
a:hover {
    color:#ff0000;
    background-color:transparent;
    text-decoration:underline;
}
a:active {
    color:#ff0000;
    background-color:transparent;
    text-decoration:underline;
}
  div[class="jumbotron"]{
    background:url("http://i.imgur.com/akCA66X.jpg");
    background-repeat: no-repeat;
    background-position: center;
    font-color:white;
    text-align:center;
    font-size:20px;
  }
  div{
    background-color: lightgrey;
  }
  h{
  color:white;
  align:left;
  }
p1{
  color:white;
}
</style>
<body>
<header>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  </header>
<div class="container">
<div class="jumbotron">
<img style="width: 200px; height: 200px; border-radius: 150px;"
<img src="http://i.imgur.com/CfGSuZ5.jpg?1" title="source: imgur.com" align="left"/>
<br>
    <h>Hello,</h>
    <p1>I'm Mariam Maher who is currently studying Business Informatics in the German University in Cairo.</p1>
</div>
<div class="row">

  <div class="col-md-4"> </div>
  <div class="col-md-4"> </div>
  </div>
  <div class="row">
  <div class="col-md-4">
  <h3 style="font-size:20px"><ins>Email:</ins></h3>
  <p>mariamm.mohamed@gmail.com</p>
  </div>
    <div class="col-md-4">
  <h4 style="font-size:20px"><ins>Phone Number:</ins></h4>
  <p>+201227878895</p>
  </div>
    <div class="col-md-4">
  <h5 style="font-size:20px"><ins>Date of Birth:</ins></h5>
  <p> 7th of August,1994</p>
  </div>
  </div>
  <%= link_to 'Take me back home', controller: 'welcome' %>
</html>

blog/app/views/welcome/Rprofile.html.erb
<!DOCTYPE html>
<title>Renad Hossam</title>
<html>
<style>
a:link {
  float:right;
  color:navy;
  aligh: right;
    background-color:transparent;
    text-decoration:none;
}
a:visited {
  color:navy;
  align:right
    background-color:transparent;
    text-decoration:none;
}
a:hover {
    color:#ff0000;
    background-color:transparent;
    text-decoration:underline;
}
a:active {
    color:#ff0000;
    background-color:transparent;
    text-decoration:underline;
}
  div[class="jumbotron"]{
    background:url("http://i.imgur.com/akCA66X.jpg");
    background-repeat: no-repeat;
    background-position: center;
    font-color:white;
    text-align:center;
    font-size:20px;
  }
  div{
    background-color: lightgrey;
  }
  h{
  color:white;
  align:left;
  }
p1{
  color:white;
}
</style>
<body>
<header>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  </header>
<div class="container">
<div class="jumbotron">
<img style="width: 200px; height: 200px; border-radius: 150px;"
<img src="http://i.imgur.com/AsvRipv.jpg?2" title="source: imgur.com" align="left"/>
<br>
    <h>Hello,</h>
    <p1>I'm Renad Hossam who is currently studying Business Informatics in the German University in Cairo.</p1>
</div>
<div class="row">

  <div class="col-md-4"> </div>
  <div class="col-md-4"> </div>
  </div>
  <div class="row">
  <div class="col-md-4">
  <h3 style="font-size:20px"><ins>Email:</ins></h3>
  <p>renad.wahdan@gmail.com</p>
  </div>
    <div class="col-md-4">
  <h4 style="font-size:20px"><ins>Phone Number:</ins></h4>
  <p>+201001833733</p>
  </div>
    <div class="col-md-4">
  <h5 style="font-size:20px"><ins>Date of Birth:</ins></h5>
  <p>9th of September,1994</p>
  </div>
  </div>
  <%= link_to 'Take me back home', controller: 'welcome' %>
</html>